DROP TABLE IF EXISTS Organizacion_externa CASCADE;
DROP TABLE IF EXISTS Entidad_Propia CASCADE;
DROP TABLE IF EXISTS Opera CASCADE;
DROP TABLE IF EXISTS Entidad_Prestadora CASCADE;

DROP TABLE IF EXISTS Recurso_Tecnologicos CASCADE;
DROP TABLE IF EXISTS Espacio_Fisico CASCADE;
DROP TABLE IF EXISTS Edificacion CASCADE;
DROP TABLE IF EXISTS Sede CASCADE;

DROP TABLE IF EXISTS cargo_menor CASCADE;
DROP TABLE IF EXISTS cargo_mayor CASCADE;
DROP TABLE IF EXISTS Familiar CASCADE;

DROP TABLE IF EXISTS Historial_Miembro CASCADE;
DROP TABLE IF EXISTS Historial_Sesiones CASCADE;
DROP TABLE IF EXISTS Historial_Contrasena CASCADE;

DROP TABLE IF EXISTS Preparador CASCADE;
DROP TABLE IF EXISTS Administrativo CASCADE;
DROP TABLE IF EXISTS Profesor CASCADE;
DROP TABLE IF EXISTS Personal_ucab CASCADE;
DROP TABLE IF EXISTS Egresado CASCADE;
DROP TABLE IF EXISTS Estudiante CASCADE;
DROP TABLE IF EXISTS Miembro CASCADE;

DROP TABLE IF EXISTS Oferta_laboral CASCADE;
DROP TABLE IF EXISTS Oferta CASCADE;

DROP TABLE IF EXISTS Servicio CASCADE;
DROP TABLE IF EXISTS Acompanante CASCADE;
DROP TABLE IF EXISTS Solicitud_servicio CASCADE;
DROP TABLE IF EXISTS Folio CASCADE;
DROP TABLE IF EXISTS Items_consumo CASCADE;
DROP TABLE IF EXISTS Historial_Reservas CASCADE;
DROP TABLE IF EXISTS Historico_Tarifa CASCADE;
DROP TABLE IF EXISTS Publica CASCADE;
DROP TABLE IF EXISTS Factura CASCADE;

DROP TABLE IF EXISTS Obtiene;
DROP TABLE IF EXISTS Zelle;
DROP TABLE IF EXISTS Criptomoneda;
DROP TABLE IF EXISTS Tarjeta;
DROP TABLE IF EXISTS Pago_Movil;
DROP TABLE IF EXISTS Efectivo;
DROP TABLE IF EXISTS TAI;


DROP TABLE IF EXISTS Metodo_Pago;
DROP TABLE IF EXISTS Tasa_Cambio;

DROP TABLE IF EXISTS Billetera_digital CASCADE; 
